<?xml version="1.0" ?>
<robot xmlns:xacro="https://ei.is.tuebingen.mpg.de/xacro">
    <!--
    Frames are defined such that they all align with the base frame when all
    joints are at position zero.

    In zero-configuration the origins of all joints are in one line.

    In zero-configuration the origin of the base link is exactly above the
    finger tip which should make it easy to place the finger in the world.
    -->

    <xacro:include filename="macros.xacro" />

    <!-- Meshes -->
    <xacro:property name="mesh_file_extension" value="stl"/>
    <xacro:property name="mesh_dir" value="package://robot_properties_manipulator/meshes/${mesh_file_extension}"/>

    <xacro:property name="upper_base_mesh" value="${mesh_dir}/SIM__BL-Finger_Base.${mesh_file_extension}"/>
    <xacro:property name="base_holder_mesh" value="${mesh_dir}/BL_Finger_Holder_SIM.${mesh_file_extension}"/>
    <xacro:property name="upper_link_mesh" value="${mesh_dir}/SIM__BL-Finger_Proximal.${mesh_file_extension}"/>
    <xacro:property name="middle_link_mesh" value="${mesh_dir}/SIM__BL-Finger_Intermediate.${mesh_file_extension}"/>
    <!-- <xacro:property name="lower_link_mesh" value="${mesh_dir}/Tip_link_Modular_SIM.${mesh_file_extension}"/> -->
    <!-- With the round tip the lower link is closer to the one of the single finger.
         TODO: set a proper mesh matching the actual link of the TriFinger. -->
    <xacro:property name="lower_link_mesh" value="${mesh_dir}/SIM_BL_FINGER_TIP_LINK.${mesh_file_extension}"/>
    <xacro:property name="tip_padding_mesh" value="${mesh_dir}/finger_padding.${mesh_file_extension}"/>

    <!-- Distance from outer edge of the link to the joint center -->
    <xacro:property name="upper_joint_center_offset" value="0.02695" />
    <xacro:property name="upper_link_length" value="0.179" />
    <xacro:property name="middle_to_lower_joint_distance" value="0.16" />
    <xacro:property name="lower_joint_to_tip_distance" value="0.16" />
    <xacro:property name="mesh_x_offset" value="0.014" />
    <xacro:property name="centre_offset" value="0.014" />
    <!--
    ROS uses meters for length. Since the new lower_link_mesh and the stage_mesh is made using millimeters as units,
    scaling them down to 1/1000 of their current size loads them with the correct size.
    -->
    <xacro:property name="lower_link_mesh_scale" value="1" />
    <xacro:property name="tip_padding" value="0" /> <!-- if this flag is set to 1 (True), finger padding is added at the finger tips -->
    <xacro:property name="base_holder" value="0" /> <!-- if this flag is set to 1 (True), an upper base_holder is added -->
    <xacro:property name="tip_mass" value="0.075" />

    <!--
    Defining the "finger" macro which is used for both single and tri-finger.
    The macro takes "suffix" as a parameter to differentiate between multiple fingers
    In case of single finger, no "suffix" value is passed.
    -->
    <xacro:macro name="finger" params="material suffix:=''">

        <!-- In case of single finger (i.e. when no suffix is passed), we change the default values of the following variables. -->
        <xacro:if value="${suffix == ''}">
            <xacro:property name="lower_link_mesh" value="${mesh_dir}/SIM_BL_FINGER_TIP_LINK.${mesh_file_extension}"/> <!-- lower_link_mesh for single finger -->
            <xacro:property name="lower_link_mesh_scale" value="1" /> <!-- not changing the scale here. Therefore, keeping the value to 1 (original scale) -->
            <xacro:property name="tip_padding" value="1" />
            <xacro:property name="base_holder" value="1" />
            <xacro:property name="tip_mass" value="0.025" />
        </xacro:if>

        <!--
        Fixed links for the finger base (parts where the upper link is mounted).
        -->
        <link name="finger_base_link${suffix}">
            <xacro:add_geometry
                origin_rpy="0 0 0"
                origin_xyz="0 ${upper_link_length} 0"
                mesh_file="${upper_base_mesh}"
                material="${material}" />
            <xacro:add_inertia
                length_x="0.05"
                length_y="0.05"
                length_z="0.05"
                mass="1"
                com="0 0 0"/>
        </link>
        <xacro:if value="${base_holder == 1}"> <!-- base_holder is added in case of single finger -->
            <link name="finger_upper_holder_link${suffix}">
                <xacro:add_geometry
                    origin_rpy="0 0 0"
                    origin_xyz="0 0 0"
                    mesh_file="${base_holder_mesh}"
                    material="${material}" />

                <!--
                  for some reason this link needs to have some inertia defined,
                  otherwise the model won't show up in gazebo
                -->

                <xacro:add_inertia
                    length_x="0.05"
                    length_y="0.05"
                    length_z="0.05"
                    mass="0.5"
                    com="0 0 0"/>
            </link>
            <joint name="finger_base_to_holder${suffix}" type="fixed">
                <parent link="finger_base_link${suffix}"/>
                <child link="finger_upper_holder_link${suffix}"/>
                <origin xyz="0 -${upper_joint_center_offset} 0" rpy="0 0 0" />
            </joint>
        </xacro:if>

        <!-- The movable links (upper, middle and lower) of the finger. -->

        <!-- TODO inertia parameters don't look correct, they cant be same for upper and middle! -->

        <link name="finger_upper_link${suffix}">
            <xacro:add_geometry
                origin_rpy="0 0 0"
                origin_xyz="0 -${upper_joint_center_offset} 0"
                mesh_file="${upper_link_mesh}"
                material="${material}" />
            <xacro:add_inertia
                length_x="0.04"
                length_y="0.14"
                length_z="0.04"
                mass="0.2"
                com="0 0.06 0"/>
        </link>

        <link name="finger_middle_link${suffix}">
            <xacro:add_geometry
                origin_rpy="${pi/2} 0 0"
                origin_xyz="${mesh_x_offset} 0 0"
                mesh_file="${middle_link_mesh}"
                material="${material}" />
            <xacro:add_inertia
                length_x="0.04"
                length_y="0.04"
                length_z="0.14"
                mass="0.2"
                com="${2 * mesh_x_offset} 0 -0.08"/>
        </link>

        <link name="finger_lower_link${suffix}">
            <xacro:add_geometry
                origin_rpy="${pi/2} 0 0"
                origin_xyz="${mesh_x_offset} 0 0"
                mesh_file="${lower_link_mesh}"
                mesh_scale="${lower_link_mesh_scale}"
                material="${material}" />
            <xacro:if value="${tip_padding == 1}"> <!-- tip_padding is added in case of single finger -->
                <xacro:add_geometry
                    origin_rpy="0 0 0"
                    origin_xyz="0 0 -${lower_joint_to_tip_distance}"
                    mesh_file="${tip_padding_mesh}"
                    material="${material}" />
            </xacro:if>
            <xacro:add_inertia
                length_x="0.02"
                length_y="0.02"
                length_z="0.14"
                mass="0.05"
                com="0 0 -0.06"/>
        </link>

        <!-- fixed link for finger tip -->
        <link name="finger_tip_link${suffix}">
            <xacro:add_inertia
                length_x="0.01"
                length_y="0.01"
                length_z="0.01"
                com="0 0 0"
                mass="${tip_mass}"/>
        </link>
        <joint name="finger_lower_to_tip_joint${suffix}" type="fixed">
            <parent link="finger_lower_link${suffix}"/>
            <child link="finger_tip_link${suffix}"/>
            <origin xyz="0 0 -${lower_joint_to_tip_distance}"/>
        </joint>


        <!-- kinematics -->
        <!-- TODO: joint limits are based on values from wiki
        (https://atlas.is.localnet/confluence/display/AMDW/Forward+Kinematics) but
        should be verified on the real system (especially the finger tip limits look
        a bit too big when visualizing the model. -->

        <joint name="finger_base_to_upper_joint${suffix}" type="revolute">
            <parent link="finger_base_link${suffix}"/>
            <child link="finger_upper_link${suffix}"/>
            <limit effort="1000" lower="-${pi/2}" upper="${pi/2}" velocity="1000"/>
            <axis xyz="0 1 0"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </joint>

        <joint name="finger_upper_to_middle_joint${suffix}" type="revolute">
            <parent link="finger_upper_link${suffix}"/>
            <child link="finger_middle_link${suffix}"/>
            <limit effort="1000" lower="${radians(-77.5)}" upper="${radians(257.5)}" velocity="1000"/>
            <axis xyz="-1 0 0"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </joint>

        <joint name="finger_middle_to_lower_joint${suffix}" type="revolute">
            <parent link="finger_middle_link${suffix}"/>
            <child link="finger_lower_link${suffix}"/>
            <limit effort="1000" lower="${radians(-172)}" upper="${radians(172)}" velocity="1000"/>
            <axis xyz="1 0 0"/>
            <origin rpy="0 0 0" xyz="0 0 -${middle_to_lower_joint_distance}"/>
        </joint>

    </xacro:macro>
</robot>
