[mainpage]
title = "robot_properties_fingers: Models of the (Tri-)Finger Robots"
auto_general_docs = false

[intersphinx.mapping]
trifinger_docs = "https://open-dynamic-robot-initiative.github.io/trifinger_docs"
